### ISSUE TITLE
DigitalOcean Image

### ISSUE THREAD

**Issue by abhiyerra** [opszero/opshell#16]
# Observation

Create DigitalOcean Images

# Expected Result

Update Packer to build a DigitalOcean image

# Why

We want to be able to work on whatever cloud environment there is.

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

- [ ] Update Packer
- [ ] Create image on DigitalOcean
- [ ] Make it so that we can build the image quickly.

 - [ ] Test It
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Send to Marketing Locations
