### ISSUE TITLE
Vagrant image

### ISSUE THREAD

**Issue by abhiyerra** [opszero/opshell#23]
# Observation:

Setup a Vagrant Image so that it appears on https://app.vagrantup.com/boxes/search

# Result:

Create a new Builder using: https://www.packer.io/docs/builders/virtualbox-iso.html in image.json

# Why:

Want to release these images for consumption via Vagrant.

# Tasks:

- [ ] Create a new Builder
- [ ] Download VirtualBox
- [ ] Build Image
- [ ] Update Makefile
- [ ] Create Pull Request

If Product:

- [ ] Update Release Notes: https://opszero.typeform.com/to/JMnLYH
