### ISSUE TITLE
Azure Image

### ISSUE THREAD

**Issue by abhiyerra** [opszero/opshell#25]
# Observation

Build Azure Image to use tool in Azure

# Expected Result

Have Packer build Azure image.

# Why

We want to be on as many clouds as possible.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

- [ ] Configure for Azure
- [ ] Build on Azure

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Send to Marketing Locations
