### ISSUE TITLE
Azure Marketplace Image

### ISSUE THREAD

**Issue by abhiyerra** [opszero/opshell#26]
# Observation

Build Images for the Azure Marketplace

# Expected Result

Have images available on Azure

# Why

Want to make it easily accessible to people wanting to use these images.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

- [ ] Create image
- [ ] Add it to Azure Marketplace
- [ ] Make it available for all clients.

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Send to Marketing Locations
