### ISSUE TITLE
Install HashCat

### ISSUE THREAD

**Issue by abhiyerra** [opszero/opshell#46]
https://hashcat.net/hashcat/

# Observation

Install HashCat

# Expected Result

Have Hashcat installed by default

# Why

It is a useful utility

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

- [ ] Install it as extras.sh

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Update Adwords
 - [ ] Send to Marketing Locations
