### ISSUE TITLE
Install Go

### ISSUE THREAD

**Issue by abhiyerra** [opszero/opshell#48]
# Observation

Install Go

# Expected Result

Include latest Golang

# Why

Useful for building stuff

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

- [ ] Install default from languages.sh

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Weebly
 - [ ] Post on Product Hunt as New Features / Screenshots
 - [ ] Update Adwords
 - [ ] Send to Marketing Locations

#53
