### ISSUE TITLE
Setup CircleCI

### ISSUE THREAD

**Issue by abhiyerra** [opszero/opshell#50]
# Observation

Setup CircleCI to automatically build the different images for different Cloud providers.

# Expected Result

Create a circle.yml file that builds and image for AWS, Azure, GCP automatically.

# Why

Need to ensure that new features build correctly.

# Blog Post

- [ ] Tell a story of the use case. Put yourself in the buyer's shoes
- [ ] The dilemma that the team sought to solve for its prospects or customers
- [ ] How are we solving it?
- [ ] What does it look like?
- [ ] How to use it?
- [ ] Reiterate the value prop

# Tasks

 - [ ] Write Blog Post
 - [ ] Build It

 - [ ] Store secrets in CircleCI
 - [ ] Makefile to build for different providers quickly and easily.

 - [ ] Test It
 - [ ] Release Blog
 - [ ] Release Notes (https://opszero.typeform.com/to/JMnLYH)
 - [ ] Update Website
 - [ ] Post on Product Hunt as New Features / Screenshots
